name: Publish GitHub Pages
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  paths:
    - .github/**.yaml
    - src/**.svelte
    - src/**.ts
    - src/**.css
    - src/**.js
    - src/**.svg
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build App
      run: npm run build

    - name: Github Pages
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: gh-pages
        keep_history: true
        build_dir: build
        jekyll: false


